const demoProducts=[{name:'Premium Kurti',seller:'Himalayan Fashion',price:1299,old:1799,off:'28% OFF',rating:'4.8',reviews:124,cat:'Fashion',emoji:'👗',image:'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=80'},{name:'Classic Sneakers',seller:'Style Nepal',price:2499,old:3200,off:'22% OFF',rating:'4.7',reviews:86,cat:'Fashion',emoji:'👟',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'},{name:'Handcrafted Necklace',seller:'Lumbini Lifestyle',price:899,old:1200,off:'25% OFF',rating:'4.9',reviews:73,cat:'Accessories',emoji:'💍',image:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80'},{name:'Everyday Tote Bag',seller:'Style Nepal',price:1150,old:1500,off:'23% OFF',rating:'4.7',reviews:61,cat:'Accessories',emoji:'👜',image:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80'},{name:'Silk Saree',seller:'Himalayan Fashion',price:3499,old:4500,off:'22% OFF',rating:'4.8',reviews:48,cat:'Fashion',emoji:'🥻',image:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80'},{name:'Classic Watch',seller:'Lumbini Lifestyle',price:1799,old:2400,off:'25% OFF',rating:'4.8',reviews:92,cat:'Accessories',emoji:'⌚',image:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80'},{name:'Beauty Essentials',seller:'Nepal Beauty Hub',price:799,old:999,off:'20% OFF',rating:'4.7',reviews:137,cat:'Beauty',emoji:'💄',image:'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80'},{name:'Traditional Topi',seller:'Local Craft Nepal',price:650,old:850,off:'24% OFF',rating:'4.9',reviews:54,cat:'Traditional',emoji:'🧢',image:'https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?auto=format&fit=crop&w=900&q=80'}];
let products=[...demoProducts];let cartItems=JSON.parse(localStorage.getItem('faishonNepalCart')||'[]');
const translations={en:{addCart:'Add to cart',contactSeller:'Contact seller',wishlistSoon:'Wishlist will be connected to your account',addedWishlist:'added to wishlist',addedCart:'added to cart',sellerChat:'Seller chat for',loginNext:'will open after login',cartEmpty:'Your cart is empty',cartItems:'Your cart has',item:'item',items:'items',searchReady:'Type to search products',adminOnly:'Admin panel'},np:{addCart:'कार्टमा राख्नुहोस्',contactSeller:'विक्रेतालाई सम्पर्क गर्नुहोस्',wishlistSoon:'विशलिस्ट तपाईंको खातासँग जोडिनेछ',addedWishlist:'विशलिस्टमा थपियो',addedCart:'कार्टमा थपियो',sellerChat:'विक्रेता च्याट',loginNext:'लगइनपछि खुल्नेछ',cartEmpty:'तपाईंको कार्ट खाली छ',cartItems:'तपाईंको कार्टमा',item:'वटा सामान',items:'वटा सामान',searchReady:'उत्पादन खोज्नुहोस्',adminOnly:'एडमिन प्यानल'}};
let lang=localStorage.getItem('faishonNepalLang')||'en';function t(k){return translations[lang][k]||translations.en[k]||k;}function money(n){return 'Rs. '+Number(n||0).toLocaleString('en-IN');}
function renderProducts(list=products){const grid=document.getElementById('productGrid');if(!grid)return;if(!list.length){grid.innerHTML='<div class="empty-products">No products found. Try another search.</div>';return;}grid.innerHTML=list.map(p=>`<article class="product"><span class="badge">${p.off||''}</span><button class="heart" aria-label="Wishlist" onclick="showToast('${String(p.name).replace(/'/g,"\\'")} '+t('addedWishlist'))">♡</button><div class="product-image"><img src="${p.image||''}" alt="${p.name}" loading="lazy" onerror="this.style.display='none';this.parentElement.classList.add('image-fallback');this.parentElement.insertAdjacentText('beforeend','${p.emoji||'🛍️'}')"></div><div class="product-body"><div class="product-cat">${p.cat||'Product'}</div><h3>${p.name}</h3><div class="seller-name">${p.seller||'FaishonNepal Seller'}</div><div class="rating">⭐ ${p.rating||'—'} <span class="seller-name">${p.reviews?`(${p.reviews})`:''}</span></div><div class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><div class="product-actions"><button class="add" onclick='addCart(${JSON.stringify(p)})'>${t('addCart')}</button><button class="contact" onclick="contactSeller('${String(p.seller||'Seller').replace(/'/g,"\\'")}')">${t('contactSeller')}</button></div></div></article>`).join('');}
async function loadLiveProducts(){try{if(!window.faishonSupabase)return;const {data,error}=await faishonSupabase.from('products').select('id,name_en,name_ne,price,mrp,stock,image_url,is_active,seller_id,category_id,created_at').eq('is_active',true).order('created_at',{ascending:false});if(error)throw error;if(data?.length){products=data.map(p=>({id:p.id,name:lang==='np'?(p.name_ne||p.name_en):p.name_en,price:Number(p.price||0),old:Number(p.mrp||0),off:p.mrp&&p.price?Math.round((1-p.price/p.mrp)*100)+'% OFF':'',rating:'—',reviews:0,cat:'Product',seller:'Verified Seller',image:p.image_url,emoji:'🛍️'}));renderProducts();}else renderProducts(demoProducts);}catch(e){console.warn('Live products unavailable:',e);renderProducts(demoProducts);}}
function searchProducts(q){q=(q||'').trim().toLowerCase();const list=!q?products:products.filter(p=>[p.name,p.seller,p.cat].some(v=>String(v||'').toLowerCase().includes(q)));renderProducts(list);}
function addCart(product){cartItems.push({...product,cartId:Date.now()+Math.random()});saveCart();showToast(product.name+' '+t('addedCart'));}
function saveCart(){localStorage.setItem('faishonNepalCart',JSON.stringify(cartItems));updateCartCount();renderCart();}
function updateCartCount(){const el=document.getElementById('cartCount');if(el)el.textContent=cartItems.length;}
function removeCart(id){cartItems=cartItems.filter(x=>String(x.cartId)!==String(id));saveCart();}
function renderCart(){const box=document.getElementById('cartItems');const total=cartItems.reduce((s,p)=>s+Number(p.price||0),0);const totalEl=document.getElementById('cartTotal');if(totalEl)totalEl.textContent=money(total);if(!box)return;box.innerHTML=cartItems.length?cartItems.map(p=>`<div class="cart-row"><img src="${p.image||''}" onerror="this.style.display='none'"><div><strong>${p.name}</strong><small>${money(p.price)}</small></div><button onclick="removeCart('${p.cartId}')">✕</button></div>`).join(''):`<div class="cart-empty">🛒<p>${t('cartEmpty')}</p></div>`;}
function openCart(){document.getElementById('cartDrawer')?.classList.add('open');document.getElementById('cartOverlay')?.classList.add('show');renderCart();}function closeCart(){document.getElementById('cartDrawer')?.classList.remove('open');document.getElementById('cartOverlay')?.classList.remove('show');}function checkoutCart(){if(!cartItems.length){showToast(t('cartEmpty'));return;}location.href='login.html';}
function contactSeller(name){showToast(t('sellerChat')+' '+name+' '+t('loginNext'));setTimeout(()=>location.href='login.html',900);}function showToast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200);}
function focusSearch(){document.getElementById('productSearch')?.focus();document.getElementById('products')?.scrollIntoView({behavior:'smooth'});}
function toggleLanguage(){lang=lang==='en'?'np':'en';localStorage.setItem('faishonNepalLang',lang);renderProducts();}
async function showAdminTab(user){try{const u=user||(await faishonSupabase.auth.getSession()).data?.session?.user;const email=(u?.email||'').toLowerCase();const tab=document.getElementById('adminTab');if(tab)tab.style.display=email==='faishonnepal@gmail.com'?'inline':'none';}catch(e){}}
async function restoreAuthSession(){try{const {data,error}=await faishonSupabase.auth.getSession();if(error)throw error;const user=data?.session?.user||null;window.currentUser=user;await showAdminTab(user);if(typeof window.updateAuthUI==='function')await window.updateAuthUI(user);return user;}catch(e){console.warn('Session restore failed',e);return null;}}
if(window.faishonSupabase?.auth){faishonSupabase.auth.onAuthStateChange((event,session)=>{if(session?.user){window.currentUser=session.user;setTimeout(()=>{showAdminTab(session.user);if(typeof window.updateAuthUI==='function')window.updateAuthUI(session.user);},0);}else if(event==='SIGNED_OUT'){window.currentUser=null;setTimeout(()=>showAdminTab(null),0);}});}
document.addEventListener('DOMContentLoaded',async()=>{updateCartCount();renderCart();renderProducts();document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const value=btn.textContent.trim();renderProducts(value==='All'?products:products.filter(p=>p.cat===value));}));await restoreAuthSession();await loadLiveProducts();});
